### ISSUE TITLE
Missing `return_depth` and `negative_text` in generate skybox method

### ISSUE THREAD

**Issue by mattrossman** [Blockade-Games/Skybox-SDK#4]
These properties are mentioned [in the docs](https://api-documentation.blockadelabs.com/api/skybox.html#generate-skybox) but are not available in the SDK client.

It may be helpful to publish an OpenAPI spec generated from the actual API implementation, so users have some source of truth to generate their own API clients from without relying on this lib to stay updated.

**Comment by KindaSloth** [comment]
Should be fixed on the last SDK version, tks for reporting it 👍🏻
