### ISSUE TITLE
Missing the new `enhance_prompt` parameter.

### ISSUE THREAD

**Issue by filandra** [Blockade-Games/Skybox-SDK#6]
The new parameter `enhance_prompt` is not implemented. Nothing happens, when this parameter is passed to generateSkybox method. The SDK should mirror the REST API endpoints, otherwise it's not useful.

**Comment by KindaSloth** [comment]
Should be fixed on the last SDK version, tks for reporting it 👍🏻

**Comment by filandra** [comment]
Great, thanks for the quick fix! 😁 👍

**Comment by filandra** [comment]
Thanks, however now when I use this new version and set `enhance_prompt` to `true`, the call is erroneous and I receive:
`Error generating skybox: InternalError { message: 'Unexpected error generating new skybox' }` :ghost: 

Works fine when set to `false` though.

**Comment by KindaSloth** [comment]
Fixed too, tks for reporting it 👍🏻

**Comment by filandra** [comment]
Tested, now it's working - thanks for the quick resolution :grin: :thumbsup:
